language: node_js

node_js:
  - '10'

install:
  - npm install -g @tarojs/cli
  - npm install

script:
  - npm run lint
  - npm run ui:ci
  - npm run test

after_script:
  - test $TRAVIS_BRANCH = master && npm run update:site

branches:
  only:
    - master
    - /^greenkeeper/.*$/

before_deploy: npm run ui:ci

deploy:
  provider: npm
  email: love@onelong.org
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    branch: master
  tag: latest

env:
  - GH_REF: github.com/loveonelong/xcandy.git
