language: node_js
node_js:
  - "10"
install:
  - npm install -g @tarojs/cli
  - npm install
script:
  - npm run eslint
  - npm run ui:ci
  - npm run test
branches:
  only:
    - master
    - /^greenkeeper/.*$/