language: node_js

node_js:
  - '10'
  - '8'

install:
  - npm install -g @tarojs/cli
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run ui:ci
  - npm run build:h5
  - npm run build:weapp

branches:
  only:
    - master
    - develop
    - /^v.*$/

jobs:
  include:
    - if: tag =~ ^v.*
      stage: npm release
      node_js: '10'
      script:
        - echo "Deploying to npm ..."
      before_deploy:
        - npm run ui:ci
        - npm version $TRAVIS_TAG --no-git-tag-version
      deploy:
        provider: npm
        email: love@onelong.org
        skip_cleanup: true
        api_key:
          secure: $NPM_TOKEN
        on:
          tags: true
          all_branches: true
        tag: latest
    - if: tag =~ ^v.*
      stage: git page
      node_js: '10'
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
          npm run update:site;
          fi

env:
  - GH_REF: github.com/xxxcandy/xcandy-ui-taro.git
