#!/bin/sh
set -e

echo 'Update Site...'

npm run build:h5
cd dist
git init
git config user.name "onelong"
git config user.email "love@onelong.org"
git add .
git commit -m "Update Site"
git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages